#pragma once

#include "driver/gpio.h"

#define RT_FW_VERSION "2.10-idf"

#define RT_EVENT_TASK_CORE 0
#define RT_LVGL_TASK_CORE 0
#define RT_LVGL_TASK_STACK_BYTES (4096 * 2)
#define RT_LVGL_TASK_PRIORITY 1
#define RT_APP_TASK_CORE 1
#define RT_APP_TASK_STACK_BYTES 8192
#define RT_APP_TASK_PRIORITY 1

#define RT_LCD_HOST SPI3_HOST
#define RT_LCD_DMA_CH SPI_DMA_CH1
#define RT_LCD_PIXEL_CLOCK_HZ (40 * 1000 * 1000)
#define RT_LCD_H_RES 480
#define RT_LCD_V_RES 320
#define RT_LCD_DRAW_BUF_ROWS 10
#define RT_LCD_SWAP_XY 1
#define RT_LCD_MIRROR_X 1
#define RT_LCD_MIRROR_Y 1
#define RT_LCD_SCK GPIO_NUM_18
#define RT_LCD_MISO GPIO_NUM_19
#define RT_LCD_MOSI GPIO_NUM_23
#define RT_LCD_DC GPIO_NUM_33
#define RT_LCD_BACKLIGHT GPIO_NUM_5
#define RT_LCD_BACKLIGHT_ON_LEVEL 0
#define RT_LCD_BACKLIGHT_OFF_LEVEL 1
#define RT_LCD_RST GPIO_NUM_27
#define RT_LCD_CS GPIO_NUM_25
#define RT_TOUCH_CS GPIO_NUM_26
#define RT_TOUCH_CAL_X0 248
#define RT_TOUCH_CAL_X1 3571
#define RT_TOUCH_CAL_Y0 202
#define RT_TOUCH_CAL_Y1 3647
#define RT_TOUCH_CAL_FLAGS 5

#define RT_I2S_OUT_NUM_BITS 32
#define RT_I2S_OUT_BCK GPIO_NUM_16
#define RT_I2S_OUT_WS GPIO_NUM_17
#define RT_I2S_OUT_DATA GPIO_NUM_21

#define RT_I2S_X_DISABLE_PIN 0
#define RT_I2S_X_DIRECTION_PIN 2
#define RT_I2S_X_STEP_PIN 1
#define RT_I2S_Y_DIRECTION_PIN 6
#define RT_I2S_Y_STEP_PIN 5
#define RT_I2S_BEEPER_PIN 7

#define RT_SCALE_RX_PIN GPIO_NUM_4
#define RT_SCALE_TX_PIN GPIO_NUM_0

#define RT_SD_SPI_SCK GPIO_NUM_14
#define RT_SD_SPI_MISO GPIO_NUM_12
#define RT_SD_SPI_MOSI GPIO_NUM_13
#define RT_SD_SPI_CS GPIO_NUM_15
#define RT_SD_DET_PIN GPIO_NUM_39
#define RT_SD_DMA_CH SPI_DMA_CH2
#define RT_SD_SPI_FREQ_KHZ 4000

#define RT_SD_MOUNT_POINT "/sdcard"
