// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#include "ui_helpers.h" 

void _ui_bar_set_property( lv_obj_t *target, int id, int val) 
{
#if LV_USE_BAR
   if (id == _UI_BAR_PROPERTY_VALUE_WITH_ANIM) lv_bar_set_value(target, val, LV_ANIM_ON);
   if (id == _UI_BAR_PROPERTY_VALUE) lv_bar_set_value(target, val, LV_ANIM_OFF);
#else
   LV_UNUSED(target);
   LV_UNUSED(id);
   LV_UNUSED(val);
#endif
}

void _ui_basic_set_property( lv_obj_t *target, int id, int val) 
{
   if (id == _UI_BASIC_PROPERTY_POSITION_X) lv_obj_set_x(target, val);
   if (id == _UI_BASIC_PROPERTY_POSITION_Y) lv_obj_set_y(target, val);
   if (id == _UI_BASIC_PROPERTY_WIDTH) lv_obj_set_width(target, val);
   if (id == _UI_BASIC_PROPERTY_HEIGHT) lv_obj_set_height(target, val);
}

void _ui_image_set_property( lv_obj_t *target, int id, uint8_t *val) 
{
#if LV_USE_IMG
   if (id == _UI_IMAGE_PROPERTY_IMAGE) lv_img_set_src(target, val);
#else
   LV_UNUSED(target);
   LV_UNUSED(id);
   LV_UNUSED(val);
#endif
}

void _ui_label_set_property( lv_obj_t *target, int id, const char *val) 
{
   if (id == _UI_LABEL_PROPERTY_TEXT) lv_label_set_text(target, val);
}

void _ui_slider_set_property( lv_obj_t *target, int id, int val) 
{
#if LV_USE_SLIDER
   if (id == _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM) lv_slider_set_value(target, val, LV_ANIM_ON);
   if (id == _UI_SLIDER_PROPERTY_VALUE) lv_slider_set_value(target, val, LV_ANIM_OFF);
#else
   LV_UNUSED(target);
   LV_UNUSED(id);
   LV_UNUSED(val);
#endif
}

void _ui_screen_change( lv_obj_t ** target, lv_scr_load_anim_t fademode, int spd, int delay, void (*target_init)(void)) 
{
   if(*target == NULL)
      target_init();
   lv_scr_load_anim(*target, fademode, spd, delay, false);
}

void _ui_screen_delete( lv_obj_t ** target ) 
{
   if(*target == NULL)
   {
      lv_obj_del(*target);
      target = NULL;
   }
}

void _ui_arc_increment( lv_obj_t *target, int val) 
{
#if LV_USE_ARC
   int old = lv_arc_get_value(target);
   lv_arc_set_value(target, old+val);
   lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, NULL);
#else
   LV_UNUSED(target);
   LV_UNUSED(val);
#endif
}

void _ui_bar_increment( lv_obj_t *target, int val, int anm) 
{
#if LV_USE_BAR
   int old = lv_bar_get_value(target);
   lv_bar_set_value(target, old+val, anm);
#else
   LV_UNUSED(target);
   LV_UNUSED(val);
   LV_UNUSED(anm);
#endif
}

void _ui_slider_increment( lv_obj_t *target, int val, int anm) 
{
#if LV_USE_SLIDER
   int old = lv_slider_get_value(target);
   lv_slider_set_value(target, old+val, anm);
   lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, NULL);
#else
   LV_UNUSED(target);
   LV_UNUSED(val);
   LV_UNUSED(anm);
#endif
}

void _ui_keyboard_set_target( lv_obj_t *keyboard, lv_obj_t *textarea) 
{
#if LV_USE_KEYBOARD
   lv_keyboard_set_textarea(keyboard, textarea);
#else
   LV_UNUSED(keyboard);
   LV_UNUSED(textarea);
#endif
}

void _ui_flag_modify( lv_obj_t *target, int32_t flag, int value)
{
    if (value==_UI_MODIFY_FLAG_TOGGLE)
    {
        if ( lv_obj_has_flag(target,flag) ) lv_obj_clear_flag(target,flag);
        else lv_obj_add_flag(target,flag);
    }
    else if (value==_UI_MODIFY_FLAG_ADD) lv_obj_add_flag(target,flag);
    else lv_obj_clear_flag(target,flag);
}
void _ui_state_modify( lv_obj_t *target, int32_t state, int value)
{
    if (value==_UI_MODIFY_STATE_TOGGLE)
    {
        if ( lv_obj_has_state(target,state) ) lv_obj_clear_state(target,state);
        else lv_obj_add_state(target,state);
    }
    else if (value==_UI_MODIFY_STATE_ADD) lv_obj_add_state(target,state);
    else lv_obj_clear_state(target,state);
}

void _ui_opacity_set( lv_obj_t *target, int val) 
{
   lv_obj_set_style_opa(target, val, 0);
}

void _ui_arc_set_text_value( lv_obj_t *trg, lv_obj_t *src, const char *prefix, const char *postfix) 
{
#if LV_USE_ARC
   char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];
   lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_arc_get_value(src), postfix);
   lv_label_set_text(trg, buf);
#else
   LV_UNUSED(trg);
   LV_UNUSED(src);
   LV_UNUSED(prefix);
   LV_UNUSED(postfix);
#endif
}

void _ui_slider_set_text_value( lv_obj_t *trg, lv_obj_t *src, const char *prefix, const char *postfix) 
{
#if LV_USE_SLIDER
   char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];
   lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_slider_get_value(src), postfix);
   lv_label_set_text(trg, buf);
#else
   LV_UNUSED(trg);
   LV_UNUSED(src);
   LV_UNUSED(prefix);
   LV_UNUSED(postfix);
#endif
}
void _ui_checked_set_text_value( lv_obj_t *trg, lv_obj_t *src, const char *txt_on, const char *txt_off) 
{
    if (lv_obj_has_state(src,LV_STATE_CHECKED)) lv_label_set_text(trg,txt_on);
    else lv_label_set_text(trg,txt_off);
}

void _ui_spinbox_step(lv_obj_t * target, int val)
{
#if LV_USE_SPINBOX
	if(val > 0) lv_spinbox_increment(target);
	else lv_spinbox_decrement(target);

	lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, NULL);
#else
   LV_UNUSED(target);
   LV_UNUSED(val);
#endif
}
