#ifndef ROBOTRICKLER_CONSTANTS_H
#define ROBOTRICKLER_CONSTANTS_H

#define ARRAY_COUNT(array) (sizeof(array) / sizeof((array)[0]))

#define MAX_PROFILE_STEPS 16
#define MAX_PROFILE_LIST_ITEMS 32
#define INFO_MESSAGE_LINES 14
#define WIFI_CREDENTIAL_SIZE 64
#define IP_ADDRESS_TEXT_SIZE 16
#define BEEPER_TEXT_SIZE 16
#define LANGUAGE_TEXT_SIZE 8
#define FW_UPDATE_URL_SIZE 128
#define SCALE_PROTOCOL_TEXT_SIZE 32
#define SCALE_CUSTOM_CODE_SIZE 32
#define PROFILE_NAME_SIZE 32
#define PROFILE_ACTUATOR_MIN 1
#define PROFILE_ACTUATOR_MAX 2
#define PROFILE_ACTUATOR_SLOTS 3

#define DEFAULT_STEPPER_RPM 100
#define DEFAULT_PROFILE_SPEED 200
#define DEFAULT_PROFILE_GENERAL_MEASUREMENTS 20
#define DEFAULT_PROFILE_STEP_MEASUREMENTS 5

#define SCALE_REQUEST_TIMEOUT_MS 2000
#define SCALE_TIMEOUT_DISPLAY_DELAY_MS 500
#define SCALE_LINE_BUFFER_SIZE 64
#define SCALE_REQUEST_BUFFER_SIZE 128
#define SCALE_REQUEST_MAX_BYTES 64
#define SCALE_WEIGHT_STABILITY_FACTOR 1000.0f

#define IDLE_SCALE_READ_INTERVAL_MS 1000UL
#define DONE_BEEP_GAP_MS 250
#define TRICKLER_INFO_LINE_SIZE 64
#define TRICKLER_INFO_TEXT_RESERVE 48
#define CONFIG_SAVE_SETTLE_DELAY_MS 100
#define RESTART_DELAY_MS 1000
#define DIAGNOSTICS_INTERVAL_MS 1000UL
#define BEEP_DONE_DURATION_MS 500
#define BEEP_BUTTON_DURATION_MS 100
#define WIFI_RECONNECT_INTERVAL_MS 10000UL
#define WIFI_RESET_DELAY_MS 500
#define WIFI_CONFIG_ERROR_DELAY_MS 3000
#define FIRMWARE_HTTP_TIMEOUT_MS 5000
#define CALIBRATION_PROFILE_NAME_SIZE 16
#define CALIBRATION_MAX_PROFILE_INDEX 999
#define CALIBRATION_PROFILE_STEP_COUNT 5
#define CALIBRATION_RS232_LIMIT_FACTOR 0.65f
#define CALIBRATION_UNITS_PER_THROW_DIVISOR 100.0f
#define CALIBRATION_MIN_STEPS 5
#define DEFAULT_SECONDARY_UNITS_PER_THROW 10.0

#define MOTOR_STEPS 200
#define MAX_TARGET_WEIGHT 999
#define EPSILON 0.00001f

#define UI_COLOR_OK 0x00FF00
#define UI_COLOR_ERROR 0xFF0000
#define UI_COLOR_WARN 0xFFFF00
#define UI_COLOR_TEXT 0xFFFFFF
#define UI_MESSAGE_BUTTON_WIDTH 100
#define UI_MESSAGE_BUTTON_HEIGHT 50
#define UI_MESSAGE_BUTTON_Y 45
#define UI_CONFIRM_BUTTON_OFFSET 70
#define UI_MESSAGE_POLL_DELAY_MS 10
#define WEIGHT_LABEL_BUFFER_SIZE 32
#define MAX_INVALID_PROFILES_SHOWN 8

#endif
