// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#include "ui.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_TabView;
lv_obj_t *ui_TabPageTrickler;
lv_obj_t *ui_PanelTarget;
lv_obj_t *ui_LabelTarget;
lv_obj_t *ui_ButtonToggleTrickler;
lv_obj_t *ui_LabelToggleTrickler;
lv_obj_t *ui_ButtonAddWeightCycle;
lv_obj_t *ui_LabelAddWeightCycle;
lv_obj_t *ui_ButtonIncreaseTargetWeight;
lv_obj_t *ui_LabelIncreaseTargetWeight;
lv_obj_t *ui_ButtonDecreaseTargetWeight;
lv_obj_t *ui_LabelDecreaseTargetWeight;
lv_obj_t *ui_PanelTricklerWeight;
lv_obj_t *ui_LabelTricklerWeight;
lv_obj_t *ui_PanelInfo;
lv_obj_t *ui_LabelInfo;
lv_obj_t *ui_TabPageProfile;
lv_obj_t *ui_PanelProfile;
lv_obj_t *ui_LabelProfile;
lv_obj_t *ui_ButtonProfileTune;
lv_obj_t *ui_LabelProfileTune;
lv_obj_t *ui_ButtonProfileDelete;
lv_obj_t *ui_LabelProfileDelete;
lv_obj_t *ui_ButtonProfilePrev;
lv_obj_t *ui_LabelProfilePrev;
lv_obj_t *ui_ButtonProfileNext;
lv_obj_t *ui_LabelProfileNext;
lv_obj_t *ui_TabPageInfo;
lv_obj_t *ui_PanelPageInfo;
lv_obj_t *ui_LabelLog;
lv_obj_t *ui_ButtonWifi;
lv_obj_t *ui_LabelWifi;
lv_obj_t *ui_ButtonScaleProtocol;
lv_obj_t *ui_LabelScaleProtocol;
lv_obj_t *ui_ButtonSyncFlashToSd;
lv_obj_t *ui_LabelSyncFlashToSd;
lv_obj_t *ui_ButtonSyncSdToFlash;
lv_obj_t *ui_LabelSyncSdToFlash;
lv_obj_t *ui_PanelMessages;
lv_obj_t *ui_ButtonMessageOk;
lv_obj_t *ui_LabelMessageOk;
lv_obj_t *ui_LabelMessages;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
lv_disp_load_scr( ui_Screen1);
}
