// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_TabView;
lv_obj_t *ui_TabPageTrickler;
lv_obj_t *ui_PanelTarget;
lv_obj_t *ui_LabelTarget;
void ui_event_ButtonToggleTrickler( lv_event_t * e);
lv_obj_t *ui_ButtonToggleTrickler;
lv_obj_t *ui_LabelToggleTrickler;
void ui_event_ButtonAddWeightFine( lv_event_t * e);
lv_obj_t *ui_ButtonAddWeightFine;
lv_obj_t *ui_LabelAddWeightFine;
void ui_event_ButtonAddWeightCycle( lv_event_t * e);
lv_obj_t *ui_ButtonAddWeightCycle;
lv_obj_t *ui_LabelAddWeightCycle;
void ui_event_ButtonAddWeightMedium( lv_event_t * e);
lv_obj_t *ui_ButtonAddWeightMedium;
lv_obj_t *ui_LabelAddWeightMedium;
void ui_event_ButtonAddWeightLarge( lv_event_t * e);
lv_obj_t *ui_ButtonAddWeightLarge;
lv_obj_t *ui_LabelAddWeightLarge;
void ui_event_ButtonIncreaseTargetWeight( lv_event_t * e);
lv_obj_t *ui_ButtonIncreaseTargetWeight;
lv_obj_t *ui_LabelIncreaseTargetWeight;
void ui_event_ButtonDecreaseTargetWeight( lv_event_t * e);
lv_obj_t *ui_ButtonDecreaseTargetWeight;
lv_obj_t *ui_LabelDecreaseTargetWeight;
lv_obj_t *ui_PanelTricklerWeight;
lv_obj_t *ui_LabelTricklerWeight;
lv_obj_t *ui_PanelInfo;
lv_obj_t *ui_LabelInfo;
lv_obj_t *ui_TabPageProfile;
lv_obj_t *ui_PanelProfile;
lv_obj_t *ui_LabelProfile;
void ui_event_ButtonProfileTune( lv_event_t * e);
lv_obj_t *ui_ButtonProfileTune;
lv_obj_t *ui_LabelProfileTune;
void ui_event_ButtonProfileDelete( lv_event_t * e);
lv_obj_t *ui_ButtonProfileDelete;
lv_obj_t *ui_LabelProfileDelete;
void ui_event_ButtonProfilePrev( lv_event_t * e);
lv_obj_t *ui_ButtonProfilePrev;
lv_obj_t *ui_LabelProfilePrev;
void ui_event_ButtonProfileNext( lv_event_t * e);
lv_obj_t *ui_ButtonProfileNext;
lv_obj_t *ui_LabelProfileNext;
lv_obj_t *ui_TabPageInfo;
lv_obj_t *ui_PanelPageInfo;
lv_obj_t *ui_LabelLog;
lv_obj_t *ui_PanelMessages;
void ui_event_ButtonMessageOk( lv_event_t * e);
lv_obj_t *ui_ButtonMessageOk;
lv_obj_t *ui_LabelMessageOk;
lv_obj_t *ui_LabelMessages;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonToggleTrickler( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      toggleTrickler_event_cb( e );
}
}
void ui_event_ButtonAddWeightFine( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      setAddWeightFine_event_cb( e );
}
}
void ui_event_ButtonAddWeightCycle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      cycleAddWeight_event_cb( e );
}
}
void ui_event_ButtonAddWeightMedium( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      setAddWeightMedium_event_cb( e );
}
}
void ui_event_ButtonAddWeightLarge( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      setAddWeightLarge_event_cb( e );
}
}
void ui_event_ButtonIncreaseTargetWeight( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      increaseTargetWeight_event_cb( e );
}
}
void ui_event_ButtonDecreaseTargetWeight( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      decreaseTargetWeight_event_cb( e );
}
}
void ui_event_ButtonProfilePrev( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      selectPreviousProfile_event_cb( e );
}
}
void ui_event_ButtonProfileTune( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      openProfileTune_event_cb( e );
}
}
void ui_event_ButtonProfileDelete( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      requestProfileDelete_event_cb( e );
}
}
void ui_event_ButtonProfileNext( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      selectNextProfile_event_cb( e );
}
}
void ui_event_ButtonMessageOk( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
if ( event_code == LV_EVENT_CLICKED) {
      messageOk_event_cb( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
