// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#ifndef _ROBOTRICKLERUI_UI_H
#define _ROBOTRICKLERUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_fonts.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
// Buttons are wired straight to their *_event_cb handlers (declared in
// ui_events.h) via LV_EVENT_CLICKED in ui_Screen1.c, so no per-button
// ui_event_* wrapper functions are needed here.
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_TabView;
extern lv_obj_t *ui_TabPageTrickler;
extern lv_obj_t *ui_PanelTarget;
extern lv_obj_t *ui_LabelTarget;
extern lv_obj_t *ui_ButtonToggleTrickler;
extern lv_obj_t *ui_LabelToggleTrickler;
extern lv_obj_t *ui_ButtonAddWeightFine;
extern lv_obj_t *ui_LabelAddWeightFine;
extern lv_obj_t *ui_ButtonAddWeightCycle;
extern lv_obj_t *ui_LabelAddWeightCycle;
extern lv_obj_t *ui_ButtonAddWeightMedium;
extern lv_obj_t *ui_LabelAddWeightMedium;
extern lv_obj_t *ui_ButtonAddWeightLarge;
extern lv_obj_t *ui_LabelAddWeightLarge;
extern lv_obj_t *ui_ButtonIncreaseTargetWeight;
extern lv_obj_t *ui_LabelIncreaseTargetWeight;
extern lv_obj_t *ui_ButtonDecreaseTargetWeight;
extern lv_obj_t *ui_LabelDecreaseTargetWeight;
extern lv_obj_t *ui_PanelTricklerWeight;
extern lv_obj_t *ui_LabelTricklerWeight;
extern lv_obj_t *ui_PanelInfo;
extern lv_obj_t *ui_LabelInfo;
extern lv_obj_t *ui_TabPageProfile;
extern lv_obj_t *ui_PanelProfile;
extern lv_obj_t *ui_LabelProfile;
extern lv_obj_t *ui_ButtonProfileTune;
extern lv_obj_t *ui_LabelProfileTune;
extern lv_obj_t *ui_ButtonProfileDelete;
extern lv_obj_t *ui_LabelProfileDelete;
extern lv_obj_t *ui_ButtonProfilePrev;
extern lv_obj_t *ui_LabelProfilePrev;
extern lv_obj_t *ui_ButtonProfileNext;
extern lv_obj_t *ui_LabelProfileNext;
extern lv_obj_t *ui_TabPageInfo;
extern lv_obj_t *ui_PanelPageInfo;
extern lv_obj_t *ui_LabelLog;
extern lv_obj_t *ui_PanelMessages;
extern lv_obj_t *ui_ButtonMessageOk;
extern lv_obj_t *ui_LabelMessageOk;
extern lv_obj_t *ui_LabelMessages;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
