// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#ifndef _ROBOTRICKLERUI_UI_H
#define _ROBOTRICKLERUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_TabView;
extern lv_obj_t *ui_TabPageTrickler;
extern lv_obj_t *ui_PanelTarget;
extern lv_obj_t *ui_LabelTarget;
void ui_event_ButtonTricklerStart( lv_event_t * e);
extern lv_obj_t *ui_ButtonTricklerStart;
extern lv_obj_t *ui_LabelTricklerStart;
void ui_event_ButtonNNN( lv_event_t * e);
extern lv_obj_t *ui_ButtonNNN;
extern lv_obj_t *ui_LabelNNN;
void ui_event_ButtonNN( lv_event_t * e);
extern lv_obj_t *ui_ButtonNN;
extern lv_obj_t *ui_LabelNN;
void ui_event_ButtonN( lv_event_t * e);
extern lv_obj_t *ui_ButtonN;
extern lv_obj_t *ui_LabelN;
void ui_event_ButtonP( lv_event_t * e);
extern lv_obj_t *ui_ButtonP;
extern lv_obj_t *ui_LabelP;
void ui_event_ButtonAdd( lv_event_t * e);
extern lv_obj_t *ui_ButtonAdd;
extern lv_obj_t *ui_LabelAdd;
void ui_event_ButtonSub( lv_event_t * e);
extern lv_obj_t *ui_ButtonSub;
extern lv_obj_t *ui_LabelSub;
extern lv_obj_t *ui_PanelTricklerWeight;
extern lv_obj_t *ui_LabelTricklerWeight;
extern lv_obj_t *ui_PanelInfo;
extern lv_obj_t *ui_LabelInfo;
extern lv_obj_t *ui_TabPageProfile;
void ui_event_RollerProfile( lv_event_t * e);
extern lv_obj_t *ui_RollerProfile;
extern lv_obj_t *ui_TabPageLogger;
extern lv_obj_t *ui_PanelLoggerWeight;
extern lv_obj_t *ui_LabelLoggerWeight;
void ui_event_ButtonLoggerStart( lv_event_t * e);
extern lv_obj_t *ui_ButtonLoggerStart;
extern lv_obj_t *ui_LabelLoggerStart;
extern lv_obj_t *ui_PanelLoggerInfo;
extern lv_obj_t *ui_LabelLoggerInfo;
extern lv_obj_t *ui_TabPageInfo;
extern lv_obj_t *ui_PanelPageInfo;
extern lv_obj_t *ui_TextAreaInfo;
extern lv_obj_t *ui_PanelMessages;
void ui_event_ButtonMessage( lv_event_t * e);
extern lv_obj_t *ui_ButtonMessage;
extern lv_obj_t *ui_LabelButtonMessage;
extern lv_obj_t *ui_LabelMessages;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
