// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void toggleTrickler_event_cb(lv_event_t * e);
void cycleAddWeight_event_cb(lv_event_t * e);
void increaseTargetWeight_event_cb(lv_event_t * e);
void decreaseTargetWeight_event_cb(lv_event_t * e);
void selectPreviousProfile_event_cb(lv_event_t * e);
void openProfileTune_event_cb(lv_event_t * e);
void requestProfileDelete_event_cb(lv_event_t * e);
void selectNextProfile_event_cb(lv_event_t * e);
void cycleScaleProtocol_event_cb(lv_event_t * e);
void syncFlashToSd_event_cb(lv_event_t * e);
void syncSdToFlash_event_cb(lv_event_t * e);
void messageOk_event_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
