#ifndef _ROBOTRICKLERUI_UI_FONTS_H
#define _ROBOTRICKLERUI_UI_FONTS_H

#include "lvgl.h"

#define UI_FONT_NORMAL (&lv_font_montserrat_18)
#define UI_FONT_LARGE (&lv_font_montserrat_34)

#define UI_SYMBOL_START LV_SYMBOL_PLAY
#define UI_SYMBOL_STOP LV_SYMBOL_STOP
#define UI_SYMBOL_YES LV_SYMBOL_OK
#define UI_SYMBOL_NO LV_SYMBOL_CLOSE
#define UI_SYMBOL_OK LV_SYMBOL_OK
#define UI_SYMBOL_SAVE LV_SYMBOL_SAVE
#define UI_SYMBOL_CANCEL LV_SYMBOL_CLOSE
#define UI_SYMBOL_TUNE LV_SYMBOL_SETTINGS
#define UI_SYMBOL_DELETE LV_SYMBOL_TRASH
#define UI_SYMBOL_PREVIOUS LV_SYMBOL_UP
#define UI_SYMBOL_NEXT LV_SYMBOL_DOWN
#define UI_SYMBOL_INCREASE LV_SYMBOL_PLUS
#define UI_SYMBOL_DECREASE LV_SYMBOL_MINUS
#define UI_SYMBOL_WIFI LV_SYMBOL_WIFI
#define UI_SYMBOL_SD_CARD LV_SYMBOL_SD_CARD

#endif
