// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView = lv_tabview_create(ui_Screen1);
lv_tabview_set_tab_bar_position(ui_TabView, LV_DIR_TOP);
lv_tabview_set_tab_bar_size(ui_TabView, UI_TOUCH_TARGET_SIZE);
lv_obj_set_width( ui_TabView, lv_pct(100));
lv_obj_set_height( ui_TabView, lv_pct(100));
lv_obj_set_align( ui_TabView, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_TabView), UI_FONT_NORMAL, LV_PART_MAIN);


ui_TabPageTrickler = lv_tabview_add_tab(ui_TabView, "Trickler");
lv_obj_set_style_pad_all(ui_TabPageTrickler, UI_TOUCH_GAP, LV_PART_MAIN);
lv_obj_clear_flag( ui_TabPageTrickler, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scroll_dir(ui_TabPageTrickler, LV_DIR_VER);
lv_obj_set_style_text_font(ui_TabPageTrickler, UI_FONT_LARGE, LV_PART_MAIN);

ui_PanelTarget = lv_obj_create(ui_TabPageTrickler);
lv_obj_set_height( ui_PanelTarget, 50);
lv_obj_set_width( ui_PanelTarget, lv_pct(100));
lv_obj_set_x( ui_PanelTarget, 0 );
lv_obj_set_y( ui_PanelTarget, -102 );
lv_obj_set_align( ui_PanelTarget, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelTarget, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelTarget = lv_label_create(ui_PanelTarget);
lv_obj_set_x( ui_LabelTarget, 0 );
lv_obj_set_y( ui_LabelTarget, 0 );
lv_obj_set_align( ui_LabelTarget, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelTarget, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelTarget,"0.000");
lv_obj_clear_flag( ui_LabelTarget, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonToggleTrickler = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_height( ui_ButtonToggleTrickler, UI_TOUCH_TARGET_SIZE);
lv_obj_set_width( ui_ButtonToggleTrickler, lv_pct(100));
lv_obj_set_x( ui_ButtonToggleTrickler, 0 );
lv_obj_set_y( ui_ButtonToggleTrickler, 72 );
lv_obj_set_align( ui_ButtonToggleTrickler, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonToggleTrickler, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonToggleTrickler, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonToggleTrickler, lv_color_hex(0x00FF00), LV_PART_MAIN);
lv_obj_set_style_bg_opa(ui_ButtonToggleTrickler, 255, LV_PART_MAIN);
lv_obj_set_style_text_color(ui_ButtonToggleTrickler, lv_color_black(), LV_PART_MAIN);

ui_LabelToggleTrickler = lv_label_create(ui_ButtonToggleTrickler);
lv_obj_set_align( ui_LabelToggleTrickler, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelToggleTrickler, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelToggleTrickler, UI_SYMBOL_START);
lv_obj_set_style_text_font(ui_LabelToggleTrickler, UI_FONT_LARGE, LV_PART_MAIN);

ui_ButtonAddWeightCycle = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_width( ui_ButtonAddWeightCycle, 148);
lv_obj_set_height( ui_ButtonAddWeightCycle, UI_TOUCH_TARGET_SIZE);
lv_obj_set_x( ui_ButtonAddWeightCycle, 0 );
lv_obj_set_y( ui_ButtonAddWeightCycle, -44 );
lv_obj_set_align( ui_ButtonAddWeightCycle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonAddWeightCycle, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonAddWeightCycle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelAddWeightCycle = lv_label_create(ui_ButtonAddWeightCycle);
lv_obj_set_align( ui_LabelAddWeightCycle, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelAddWeightCycle, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelAddWeightCycle,"0.100");

ui_ButtonIncreaseTargetWeight = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_height( ui_ButtonIncreaseTargetWeight, UI_TOUCH_TARGET_SIZE);
lv_obj_set_width( ui_ButtonIncreaseTargetWeight, 148);
lv_obj_set_x( ui_ButtonIncreaseTargetWeight, -156 );
lv_obj_set_y( ui_ButtonIncreaseTargetWeight, -44 );
lv_obj_set_align( ui_ButtonIncreaseTargetWeight, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonIncreaseTargetWeight, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonIncreaseTargetWeight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelIncreaseTargetWeight = lv_label_create(ui_ButtonIncreaseTargetWeight);
lv_obj_set_align( ui_LabelIncreaseTargetWeight, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelIncreaseTargetWeight, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelIncreaseTargetWeight, UI_SYMBOL_INCREASE);
lv_obj_set_style_text_font(ui_LabelIncreaseTargetWeight, UI_FONT_LARGE, LV_PART_MAIN);

ui_ButtonDecreaseTargetWeight = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_height( ui_ButtonDecreaseTargetWeight, UI_TOUCH_TARGET_SIZE);
lv_obj_set_width( ui_ButtonDecreaseTargetWeight, 148);
lv_obj_set_x( ui_ButtonDecreaseTargetWeight, 156 );
lv_obj_set_y( ui_ButtonDecreaseTargetWeight, -44 );
lv_obj_set_align( ui_ButtonDecreaseTargetWeight, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonDecreaseTargetWeight, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonDecreaseTargetWeight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelDecreaseTargetWeight = lv_label_create(ui_ButtonDecreaseTargetWeight);
lv_obj_set_x( ui_LabelDecreaseTargetWeight, 1 );
lv_obj_set_y( ui_LabelDecreaseTargetWeight, -4 );
lv_obj_set_align( ui_LabelDecreaseTargetWeight, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelDecreaseTargetWeight, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelDecreaseTargetWeight, UI_SYMBOL_DECREASE);
lv_obj_set_style_text_font(ui_LabelDecreaseTargetWeight, UI_FONT_LARGE, LV_PART_MAIN);

ui_PanelTricklerWeight = lv_obj_create(ui_TabPageTrickler);
lv_obj_set_height( ui_PanelTricklerWeight, 50);
lv_obj_set_width( ui_PanelTricklerWeight, lv_pct(100));
lv_obj_set_x( ui_PanelTricklerWeight, 0 );
lv_obj_set_y( ui_PanelTricklerWeight, 14 );
lv_obj_set_align( ui_PanelTricklerWeight, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelTricklerWeight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelTricklerWeight = lv_label_create(ui_PanelTricklerWeight);
lv_obj_set_x( ui_LabelTricklerWeight, 0 );
lv_obj_set_y( ui_LabelTricklerWeight, 0 );
lv_obj_set_align( ui_LabelTricklerWeight, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelTricklerWeight, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelTricklerWeight,"-.-");
lv_obj_clear_flag( ui_LabelTricklerWeight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelInfo = lv_obj_create(ui_TabPageTrickler);
lv_obj_set_height( ui_PanelInfo, 26);
lv_obj_set_width( ui_PanelInfo, lv_pct(100));
lv_obj_set_x( ui_PanelInfo, 0 );
lv_obj_set_y( ui_PanelInfo, 112 );
lv_obj_set_align( ui_PanelInfo, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_PanelInfo, UI_FONT_NORMAL, LV_PART_MAIN);

ui_LabelInfo = lv_label_create(ui_PanelInfo);
lv_obj_set_width( ui_LabelInfo, lv_pct(95));
lv_obj_set_height( ui_LabelInfo, 24);
lv_obj_set_align( ui_LabelInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelInfo,"Robo-Trickler // strenuous.dev");
lv_label_set_long_mode(ui_LabelInfo, LV_LABEL_LONG_MODE_DOTS);
lv_obj_set_style_text_align(ui_LabelInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_clear_flag( ui_LabelInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabPageProfile = lv_tabview_add_tab(ui_TabView, "Profile");
lv_obj_set_style_pad_all(ui_TabPageProfile, UI_TOUCH_GAP, LV_PART_MAIN);
lv_obj_clear_flag( ui_TabPageProfile, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_TabPageProfile, UI_FONT_LARGE, LV_PART_MAIN);

ui_PanelProfile = lv_obj_create(ui_TabPageProfile);
lv_obj_set_style_pad_all(ui_PanelProfile, UI_TOUCH_GAP, LV_PART_MAIN);
lv_obj_set_height( ui_PanelProfile, 75);
lv_obj_set_width( ui_PanelProfile, lv_pct(100));
lv_obj_set_align( ui_PanelProfile, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelProfile, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelProfile = lv_label_create(ui_PanelProfile);
lv_obj_set_width( ui_LabelProfile, 280);
lv_obj_set_height( ui_LabelProfile, 45);
lv_obj_set_align( ui_LabelProfile, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelProfile,"Profile");
lv_label_set_long_mode(ui_LabelProfile, LV_LABEL_LONG_MODE_DOTS);
lv_obj_set_style_text_align(ui_LabelProfile, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

ui_ButtonProfileTune = lv_btn_create(ui_PanelProfile);
lv_obj_set_width( ui_ButtonProfileTune, 58);
lv_obj_set_height( ui_ButtonProfileTune, 58);
lv_obj_set_x( ui_ButtonProfileTune, 0);
lv_obj_set_align( ui_ButtonProfileTune, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ButtonProfileTune, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonProfileTune, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonProfileTune, lv_color_hex(0xFF9900), LV_PART_MAIN);
lv_obj_set_style_bg_opa(ui_ButtonProfileTune, 255, LV_PART_MAIN);
lv_obj_set_style_text_color(ui_ButtonProfileTune, lv_color_black(), LV_PART_MAIN);

ui_LabelProfileTune = lv_label_create(ui_ButtonProfileTune);
lv_obj_set_align( ui_LabelProfileTune, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelProfileTune, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelProfileTune, UI_SYMBOL_TUNE);
lv_obj_set_style_text_align(ui_LabelProfileTune, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_set_style_text_font(ui_LabelProfileTune, UI_FONT_LARGE, LV_PART_MAIN);

ui_ButtonProfileDelete = lv_btn_create(ui_PanelProfile);
lv_obj_set_width( ui_ButtonProfileDelete, 58);
lv_obj_set_height( ui_ButtonProfileDelete, 58);
lv_obj_set_x( ui_ButtonProfileDelete, 0);
lv_obj_set_align( ui_ButtonProfileDelete, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ButtonProfileDelete, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonProfileDelete, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonProfileDelete, lv_color_hex(0xFF0000), LV_PART_MAIN);
lv_obj_set_style_bg_opa(ui_ButtonProfileDelete, 255, LV_PART_MAIN);
lv_obj_set_style_text_color(ui_ButtonProfileDelete, lv_color_black(), LV_PART_MAIN);

ui_LabelProfileDelete = lv_label_create(ui_ButtonProfileDelete);
lv_obj_set_align( ui_LabelProfileDelete, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelProfileDelete, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelProfileDelete, UI_SYMBOL_DELETE);
lv_obj_set_style_text_align(ui_LabelProfileDelete, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_set_style_text_font(ui_LabelProfileDelete, UI_FONT_LARGE, LV_PART_MAIN);

ui_ButtonProfilePrev = lv_btn_create(ui_TabPageProfile);
lv_obj_set_height( ui_ButtonProfilePrev, 75);
lv_obj_set_width( ui_ButtonProfilePrev, lv_pct(100));
lv_obj_set_align( ui_ButtonProfilePrev, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ButtonProfilePrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonProfilePrev, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelProfilePrev = lv_label_create(ui_ButtonProfilePrev);
lv_obj_set_align( ui_LabelProfilePrev, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelProfilePrev, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelProfilePrev, UI_SYMBOL_PREVIOUS);
lv_obj_set_style_text_align(ui_LabelProfilePrev, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_set_style_text_font(ui_LabelProfilePrev, UI_FONT_LARGE, LV_PART_MAIN);

ui_ButtonProfileNext = lv_btn_create(ui_TabPageProfile);
lv_obj_set_height( ui_ButtonProfileNext, 75);
lv_obj_set_width( ui_ButtonProfileNext, lv_pct(100));
lv_obj_set_align( ui_ButtonProfileNext, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_ButtonProfileNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonProfileNext, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelProfileNext = lv_label_create(ui_ButtonProfileNext);
lv_obj_set_align( ui_LabelProfileNext, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelProfileNext, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelProfileNext, UI_SYMBOL_NEXT);
lv_obj_set_style_text_align(ui_LabelProfileNext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_set_style_text_font(ui_LabelProfileNext, UI_FONT_LARGE, LV_PART_MAIN);

ui_TabPageInfo = lv_tabview_add_tab(ui_TabView, "Info");
lv_obj_set_style_pad_all(ui_TabPageInfo, UI_TOUCH_GAP, LV_PART_MAIN);
lv_obj_clear_flag( ui_TabPageInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelPageInfo = lv_obj_create(ui_TabPageInfo);
lv_obj_set_style_pad_all(ui_PanelPageInfo, 0, LV_PART_MAIN);
lv_obj_set_style_border_width(ui_PanelPageInfo, 0, LV_PART_MAIN);
lv_obj_set_width( ui_PanelPageInfo, lv_pct(100));
lv_obj_set_height( ui_PanelPageInfo, lv_pct(100));
lv_obj_set_align( ui_PanelPageInfo, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPageInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_PanelPageInfo, LV_SCROLLBAR_MODE_OFF);

ui_LabelLog = lv_label_create(ui_PanelPageInfo);
lv_obj_set_width( ui_LabelLog, lv_pct(100));
lv_obj_set_height( ui_LabelLog, 196);
lv_obj_set_align( ui_LabelLog, LV_ALIGN_TOP_MID );
lv_label_set_long_mode(ui_LabelLog, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelLog,"");

ui_ButtonWifi = lv_btn_create(ui_PanelPageInfo);
lv_obj_set_width( ui_ButtonWifi, UI_TOUCH_TARGET_SIZE);
lv_obj_set_height( ui_ButtonWifi, UI_TOUCH_TARGET_SIZE);
lv_obj_set_x( ui_ButtonWifi, 178 );
lv_obj_set_y( ui_ButtonWifi, 0 );
lv_obj_set_align( ui_ButtonWifi, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_ButtonWifi, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );
lv_obj_clear_flag( ui_ButtonWifi, LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_bg_color(ui_ButtonWifi, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonWifi, lv_color_hex(0x219653), LV_PART_MAIN | LV_STATE_CHECKED);

ui_LabelWifi = lv_label_create(ui_ButtonWifi);
lv_obj_set_align( ui_LabelWifi, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelWifi, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelWifi, UI_SYMBOL_WIFI);
lv_obj_set_style_text_font(ui_LabelWifi, UI_FONT_NORMAL, LV_PART_MAIN);

ui_ButtonScaleProtocol = lv_btn_create(ui_PanelPageInfo);
lv_obj_set_width( ui_ButtonScaleProtocol, 170);
lv_obj_set_height( ui_ButtonScaleProtocol, UI_TOUCH_TARGET_SIZE);
lv_obj_set_x( ui_ButtonScaleProtocol, 0 );
lv_obj_set_y( ui_ButtonScaleProtocol, 0 );
lv_obj_set_align( ui_ButtonScaleProtocol, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_ButtonScaleProtocol, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonScaleProtocol, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelScaleProtocol = lv_label_create(ui_ButtonScaleProtocol);
lv_obj_set_width( ui_LabelScaleProtocol, lv_pct(100));
lv_obj_set_height( ui_LabelScaleProtocol, 24);
lv_obj_set_align( ui_LabelScaleProtocol, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelScaleProtocol,"Scale: --");
lv_label_set_long_mode(ui_LabelScaleProtocol, LV_LABEL_LONG_MODE_DOTS);
lv_obj_set_style_text_align(ui_LabelScaleProtocol, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_set_style_text_font(ui_LabelScaleProtocol, UI_FONT_NORMAL, LV_PART_MAIN);

ui_ButtonSyncFlashToSd = lv_btn_create(ui_PanelPageInfo);
lv_obj_set_width( ui_ButtonSyncFlashToSd, 110);
lv_obj_set_height( ui_ButtonSyncFlashToSd, UI_TOUCH_TARGET_SIZE);
lv_obj_set_x( ui_ButtonSyncFlashToSd, 236 );
lv_obj_set_y( ui_ButtonSyncFlashToSd, 0 );
lv_obj_set_align( ui_ButtonSyncFlashToSd, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_ButtonSyncFlashToSd, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSyncFlashToSd, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelSyncFlashToSd = lv_label_create(ui_ButtonSyncFlashToSd);
lv_obj_set_align( ui_LabelSyncFlashToSd, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelSyncFlashToSd, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelSyncFlashToSd, UI_TEXT_SYNC_FLASH_TO_SD);
lv_obj_set_style_text_font(ui_LabelSyncFlashToSd, UI_FONT_NORMAL, LV_PART_MAIN);

ui_ButtonSyncSdToFlash = lv_btn_create(ui_PanelPageInfo);
lv_obj_set_width( ui_ButtonSyncSdToFlash, 110);
lv_obj_set_height( ui_ButtonSyncSdToFlash, UI_TOUCH_TARGET_SIZE);
lv_obj_set_x( ui_ButtonSyncSdToFlash, 354 );
lv_obj_set_y( ui_ButtonSyncSdToFlash, 0 );
lv_obj_set_align( ui_ButtonSyncSdToFlash, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_ButtonSyncSdToFlash, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSyncSdToFlash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelSyncSdToFlash = lv_label_create(ui_ButtonSyncSdToFlash);
lv_obj_set_align( ui_LabelSyncSdToFlash, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelSyncSdToFlash, LV_LABEL_LONG_CLIP);
lv_label_set_text_static(ui_LabelSyncSdToFlash, UI_TEXT_SYNC_SD_TO_FLASH);
lv_obj_set_style_text_font(ui_LabelSyncSdToFlash, UI_FONT_NORMAL, LV_PART_MAIN);

/* The message/confirm dialog (ui_PanelMessages and its children) is built
   lazily in ui_dialogs.ino and deleted on close to keep the LVGL pool free
   while no dialog is shown. */

lv_obj_add_event_cb(ui_ButtonToggleTrickler, toggleTrickler_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonAddWeightCycle, cycleAddWeight_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonIncreaseTargetWeight, increaseTargetWeight_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonDecreaseTargetWeight, decreaseTargetWeight_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonProfileTune, openProfileTune_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonProfileDelete, requestProfileDelete_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonProfilePrev, selectPreviousProfile_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonProfileNext, selectNextProfile_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonScaleProtocol, cycleScaleProtocol_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonWifi, toggleWifi_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonSyncFlashToSd, syncFlashToSd_event_cb, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_ButtonSyncSdToFlash, syncSdToFlash_event_cb, LV_EVENT_CLICKED, NULL);

prepareTouchControls(ui_TabView);
}
