// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView = lv_tabview_create(ui_Screen1);
lv_tabview_set_tab_bar_position(ui_TabView, LV_DIR_TOP);
lv_tabview_set_tab_bar_size(ui_TabView, 35);
lv_obj_set_width( ui_TabView, lv_pct(100));
lv_obj_set_height( ui_TabView, lv_pct(100));
lv_obj_set_align( ui_TabView, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_TabView, &lv_font_montserrat_16, LV_PART_MAIN);


ui_TabPageTrickler = lv_tabview_add_tab(ui_TabView, "Trickler");
lv_obj_clear_flag( ui_TabPageTrickler, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scroll_dir(ui_TabPageTrickler, LV_DIR_VER);
lv_obj_set_style_text_font(ui_TabPageTrickler, &lv_font_montserrat_32, LV_PART_MAIN);

ui_PanelTarget = lv_obj_create(ui_TabPageTrickler);
lv_obj_set_height( ui_PanelTarget, 50);
lv_obj_set_width( ui_PanelTarget, lv_pct(100));
lv_obj_set_x( ui_PanelTarget, 0 );
lv_obj_set_y( ui_PanelTarget, -106 );
lv_obj_set_align( ui_PanelTarget, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelTarget, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelTarget = lv_label_create(ui_PanelTarget);
lv_obj_set_width( ui_LabelTarget, lv_pct(100));
lv_obj_set_height( ui_LabelTarget, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelTarget, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTarget,"0.000");
lv_obj_clear_flag( ui_LabelTarget, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_align(ui_LabelTarget, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

ui_ButtonToggleTrickler = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_height( ui_ButtonToggleTrickler, 50);
lv_obj_set_width( ui_ButtonToggleTrickler, lv_pct(100));
lv_obj_set_x( ui_ButtonToggleTrickler, 0 );
lv_obj_set_y( ui_ButtonToggleTrickler, 68 );
lv_obj_set_align( ui_ButtonToggleTrickler, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonToggleTrickler, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonToggleTrickler, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonToggleTrickler, lv_color_hex(0x00FF00), LV_PART_MAIN);
lv_obj_set_style_bg_opa(ui_ButtonToggleTrickler, 255, LV_PART_MAIN);

ui_LabelToggleTrickler = lv_label_create(ui_ButtonToggleTrickler);
lv_obj_set_width( ui_LabelToggleTrickler, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelToggleTrickler, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelToggleTrickler, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelToggleTrickler,"Start");

ui_ButtonAddWeightFine = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_width( ui_ButtonAddWeightFine, 100);
lv_obj_set_height( ui_ButtonAddWeightFine, 50);
lv_obj_set_x( ui_ButtonAddWeightFine, -173 );
lv_obj_set_y( ui_ButtonAddWeightFine, -48 );
lv_obj_set_align( ui_ButtonAddWeightFine, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonAddWeightFine, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonAddWeightFine, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelAddWeightFine = lv_label_create(ui_ButtonAddWeightFine);
lv_obj_set_width( ui_LabelAddWeightFine, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAddWeightFine, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelAddWeightFine, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAddWeightFine,"0.001");

ui_ButtonAddWeightCycle = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_width( ui_ButtonAddWeightCycle, 150);
lv_obj_set_height( ui_ButtonAddWeightCycle, 50);
lv_obj_set_x( ui_ButtonAddWeightCycle, 0 );
lv_obj_set_y( ui_ButtonAddWeightCycle, -48 );
lv_obj_set_align( ui_ButtonAddWeightCycle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonAddWeightCycle, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonAddWeightCycle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelAddWeightCycle = lv_label_create(ui_ButtonAddWeightCycle);
lv_obj_set_width( ui_LabelAddWeightCycle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAddWeightCycle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelAddWeightCycle, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAddWeightCycle,"0.100");

ui_ButtonAddWeightMedium = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_width( ui_ButtonAddWeightMedium, 100);
lv_obj_set_height( ui_ButtonAddWeightMedium, 50);
lv_obj_set_x( ui_ButtonAddWeightMedium, 58 );
lv_obj_set_y( ui_ButtonAddWeightMedium, -48 );
lv_obj_set_align( ui_ButtonAddWeightMedium, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonAddWeightMedium, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonAddWeightMedium, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelAddWeightMedium = lv_label_create(ui_ButtonAddWeightMedium);
lv_obj_set_width( ui_LabelAddWeightMedium, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAddWeightMedium, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelAddWeightMedium, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAddWeightMedium,"0.1");

ui_ButtonAddWeightLarge = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_width( ui_ButtonAddWeightLarge, 100);
lv_obj_set_height( ui_ButtonAddWeightLarge, 50);
lv_obj_set_x( ui_ButtonAddWeightLarge, 173 );
lv_obj_set_y( ui_ButtonAddWeightLarge, -48 );
lv_obj_set_align( ui_ButtonAddWeightLarge, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonAddWeightLarge, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonAddWeightLarge, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelAddWeightLarge = lv_label_create(ui_ButtonAddWeightLarge);
lv_obj_set_width( ui_LabelAddWeightLarge, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAddWeightLarge, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelAddWeightLarge, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAddWeightLarge,"1.0");

ui_ButtonIncreaseTargetWeight = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_height( ui_ButtonIncreaseTargetWeight, 50);
lv_obj_set_width( ui_ButtonIncreaseTargetWeight, 150);
lv_obj_set_x( ui_ButtonIncreaseTargetWeight, -165 );
lv_obj_set_y( ui_ButtonIncreaseTargetWeight, -48 );
lv_obj_set_align( ui_ButtonIncreaseTargetWeight, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonIncreaseTargetWeight, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonIncreaseTargetWeight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelIncreaseTargetWeight = lv_label_create(ui_ButtonIncreaseTargetWeight);
lv_obj_set_width( ui_LabelIncreaseTargetWeight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelIncreaseTargetWeight, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelIncreaseTargetWeight, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelIncreaseTargetWeight, LV_SYMBOL_PLUS);
lv_obj_set_style_text_font(ui_LabelIncreaseTargetWeight, &lv_font_montserrat_46, LV_PART_MAIN);

ui_ButtonDecreaseTargetWeight = lv_btn_create(ui_TabPageTrickler);
lv_obj_set_height( ui_ButtonDecreaseTargetWeight, 50);
lv_obj_set_width( ui_ButtonDecreaseTargetWeight, 150);
lv_obj_set_x( ui_ButtonDecreaseTargetWeight, 165 );
lv_obj_set_y( ui_ButtonDecreaseTargetWeight, -48 );
lv_obj_set_align( ui_ButtonDecreaseTargetWeight, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonDecreaseTargetWeight, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonDecreaseTargetWeight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelDecreaseTargetWeight = lv_label_create(ui_ButtonDecreaseTargetWeight);
lv_obj_set_width( ui_LabelDecreaseTargetWeight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDecreaseTargetWeight, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelDecreaseTargetWeight, 1 );
lv_obj_set_y( ui_LabelDecreaseTargetWeight, -4 );
lv_obj_set_align( ui_LabelDecreaseTargetWeight, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDecreaseTargetWeight, LV_SYMBOL_MINUS);
lv_obj_set_style_text_font(ui_LabelDecreaseTargetWeight, &lv_font_montserrat_46, LV_PART_MAIN);

ui_PanelTricklerWeight = lv_obj_create(ui_TabPageTrickler);
lv_obj_set_height( ui_PanelTricklerWeight, 50);
lv_obj_set_width( ui_PanelTricklerWeight, lv_pct(100));
lv_obj_set_x( ui_PanelTricklerWeight, 0 );
lv_obj_set_y( ui_PanelTricklerWeight, 10 );
lv_obj_set_align( ui_PanelTricklerWeight, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelTricklerWeight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelTricklerWeight = lv_label_create(ui_PanelTricklerWeight);
lv_obj_set_width( ui_LabelTricklerWeight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTricklerWeight, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTricklerWeight, 0 );
lv_obj_set_y( ui_LabelTricklerWeight, -4 );
lv_obj_set_align( ui_LabelTricklerWeight, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTricklerWeight,"-.-");
lv_obj_clear_flag( ui_LabelTricklerWeight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelInfo = lv_obj_create(ui_TabPageTrickler);
lv_obj_set_height( ui_PanelInfo, 30);
lv_obj_set_width( ui_PanelInfo, lv_pct(100));
lv_obj_set_x( ui_PanelInfo, 0 );
lv_obj_set_y( ui_PanelInfo, 116 );
lv_obj_set_align( ui_PanelInfo, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_PanelInfo, &lv_font_montserrat_16, LV_PART_MAIN);

ui_LabelInfo = lv_label_create(ui_PanelInfo);
lv_obj_set_width( ui_LabelInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelInfo,"Robo-Trickler // strenuous.dev");
lv_obj_clear_flag( ui_LabelInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabPageProfile = lv_tabview_add_tab(ui_TabView, "Profile");
lv_obj_clear_flag( ui_TabPageProfile, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_TabPageProfile, &lv_font_montserrat_32, LV_PART_MAIN);

ui_PanelProfile = lv_obj_create(ui_TabPageProfile);
lv_obj_set_height( ui_PanelProfile, 75);
lv_obj_set_width( ui_PanelProfile, lv_pct(100));
lv_obj_set_align( ui_PanelProfile, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelProfile, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelProfile = lv_label_create(ui_PanelProfile);
lv_obj_set_width( ui_LabelProfile, lv_pct(100));
lv_obj_set_height( ui_LabelProfile, lv_pct(100));
lv_obj_set_align( ui_LabelProfile, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelProfile,"Profile");
lv_obj_set_style_text_align(ui_LabelProfile, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

ui_ButtonProfileTune = lv_btn_create(ui_PanelProfile);
lv_obj_set_width( ui_ButtonProfileTune, 75);
lv_obj_set_height( ui_ButtonProfileTune, 75);
lv_obj_set_x( ui_ButtonProfileTune, -15);
lv_obj_set_align( ui_ButtonProfileTune, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ButtonProfileTune, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonProfileTune, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonProfileTune, lv_color_hex(0xFF9900), LV_PART_MAIN);
lv_obj_set_style_bg_opa(ui_ButtonProfileTune, 255, LV_PART_MAIN);

ui_LabelProfileTune = lv_label_create(ui_ButtonProfileTune);
lv_obj_set_width( ui_LabelProfileTune, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelProfileTune, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelProfileTune, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelProfileTune, LV_SYMBOL_SETTINGS);
lv_obj_set_style_text_align(ui_LabelProfileTune, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_set_style_text_font(ui_LabelProfileTune, &lv_font_montserrat_46, LV_PART_MAIN);

ui_ButtonProfileDelete = lv_btn_create(ui_PanelProfile);
lv_obj_set_width( ui_ButtonProfileDelete, 75);
lv_obj_set_height( ui_ButtonProfileDelete, 75);
lv_obj_set_x( ui_ButtonProfileDelete, 15);
lv_obj_set_align( ui_ButtonProfileDelete, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ButtonProfileDelete, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonProfileDelete, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonProfileDelete, lv_color_hex(0xFF0000), LV_PART_MAIN);
lv_obj_set_style_bg_opa(ui_ButtonProfileDelete, 255, LV_PART_MAIN);

ui_LabelProfileDelete = lv_label_create(ui_ButtonProfileDelete);
lv_obj_set_width( ui_LabelProfileDelete, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelProfileDelete, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelProfileDelete, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelProfileDelete, LV_SYMBOL_TRASH);
lv_obj_set_style_text_align(ui_LabelProfileDelete, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_set_style_text_font(ui_LabelProfileDelete, &lv_font_montserrat_46, LV_PART_MAIN);

ui_ButtonProfilePrev = lv_btn_create(ui_TabPageProfile);
lv_obj_set_height( ui_ButtonProfilePrev, 75);
lv_obj_set_width( ui_ButtonProfilePrev, lv_pct(100));
lv_obj_set_align( ui_ButtonProfilePrev, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ButtonProfilePrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonProfilePrev, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelProfilePrev = lv_label_create(ui_ButtonProfilePrev);
lv_obj_set_width( ui_LabelProfilePrev, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelProfilePrev, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelProfilePrev, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelProfilePrev, LV_SYMBOL_UP);
lv_obj_set_style_text_align(ui_LabelProfilePrev, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_set_style_text_font(ui_LabelProfilePrev, &lv_font_montserrat_46, LV_PART_MAIN);

ui_ButtonProfileNext = lv_btn_create(ui_TabPageProfile);
lv_obj_set_height( ui_ButtonProfileNext, 75);
lv_obj_set_width( ui_ButtonProfileNext, lv_pct(100));
lv_obj_set_align( ui_ButtonProfileNext, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_ButtonProfileNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonProfileNext, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelProfileNext = lv_label_create(ui_ButtonProfileNext);
lv_obj_set_width( ui_LabelProfileNext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelProfileNext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelProfileNext, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelProfileNext, LV_SYMBOL_DOWN);
lv_obj_set_style_text_align(ui_LabelProfileNext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_set_style_text_font(ui_LabelProfileNext, &lv_font_montserrat_46, LV_PART_MAIN);

ui_TabPageInfo = lv_tabview_add_tab(ui_TabView, "Info");
lv_obj_clear_flag( ui_TabPageInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelPageInfo = lv_obj_create(ui_TabPageInfo);
lv_obj_set_width( ui_PanelPageInfo, lv_pct(105));
lv_obj_set_height( ui_PanelPageInfo, lv_pct(110));
lv_obj_set_align( ui_PanelPageInfo, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPageInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_PanelPageInfo, LV_SCROLLBAR_MODE_OFF);

ui_LabelLog = lv_label_create(ui_PanelPageInfo);
lv_obj_set_width( ui_LabelLog, lv_pct(100));
lv_obj_set_height( ui_LabelLog, lv_pct(100));
lv_obj_set_align( ui_LabelLog, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelLog,"");

ui_PanelMessages = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_PanelMessages, lv_pct(90));
lv_obj_set_height( ui_PanelMessages, lv_pct(60));
lv_obj_set_align( ui_PanelMessages, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PanelMessages, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PanelMessages, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonMessageOk = lv_btn_create(ui_PanelMessages);
lv_obj_set_width( ui_ButtonMessageOk, 100);
lv_obj_set_height( ui_ButtonMessageOk, 50);
lv_obj_set_x( ui_ButtonMessageOk, 0 );
lv_obj_set_y( ui_ButtonMessageOk, 45 );
lv_obj_set_align( ui_ButtonMessageOk, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonMessageOk, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonMessageOk, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelMessageOk = lv_label_create(ui_ButtonMessageOk);
lv_obj_set_width( ui_LabelMessageOk, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMessageOk, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelMessageOk, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMessageOk,"OK");

ui_LabelMessages = lv_label_create(ui_PanelMessages);
lv_obj_set_width( ui_LabelMessages, lv_pct(100));
lv_obj_set_height( ui_LabelMessages, lv_pct(60));
lv_obj_set_align( ui_LabelMessages, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LabelMessages,"Test Info");
lv_obj_set_style_text_align(ui_LabelMessages, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
lv_obj_set_style_text_font(ui_LabelMessages, &lv_font_montserrat_32, LV_PART_MAIN);
lv_obj_set_style_text_color(ui_LabelMessages, lv_color_hex(0xFF0000), LV_PART_MAIN);

lv_obj_add_event_cb(ui_ButtonToggleTrickler, ui_event_ButtonToggleTrickler, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonAddWeightFine, ui_event_ButtonAddWeightFine, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonAddWeightCycle, ui_event_ButtonAddWeightCycle, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonAddWeightMedium, ui_event_ButtonAddWeightMedium, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonAddWeightLarge, ui_event_ButtonAddWeightLarge, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonIncreaseTargetWeight, ui_event_ButtonIncreaseTargetWeight, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonDecreaseTargetWeight, ui_event_ButtonDecreaseTargetWeight, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonProfileTune, ui_event_ButtonProfileTune, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonProfileDelete, ui_event_ButtonProfileDelete, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonProfilePrev, ui_event_ButtonProfilePrev, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonProfileNext, ui_event_ButtonProfileNext, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonMessageOk, ui_event_ButtonMessageOk, LV_EVENT_ALL, NULL);

}
