// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#ifndef _ROBOTRICKLERUI_UI_H
#define _ROBOTRICKLERUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_TabPage1;
void ui_event_ButtonStart( lv_event_t * e);
extern lv_obj_t *ui_ButtonStart;
extern lv_obj_t *ui_LabelStart;
extern lv_obj_t *ui_TabPage2;
extern lv_obj_t *ui_TabPage3;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
