// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void trickler_start_event_cb(lv_event_t * e);
void nnn_event_cb(lv_event_t * e);
void nn_event_cb(lv_event_t * e);
void n_event_cb(lv_event_t * e);
void p_event_cb(lv_event_t * e);
void add_event_cb(lv_event_t * e);
void sub_event_cb(lv_event_t * e);
void profile_event_cb(lv_event_t * e);
void logger_start_event_cb(lv_event_t * e);
void message_event_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
