// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#include "ui.h"

void trickler_start_event_cb(lv_event_t * e)
{
	// Your code here
}

void nnn_event_cb(lv_event_t * e)
{
	// Your code here
}

void nn_event_cb(lv_event_t * e)
{
	// Your code here
}

void n_event_cb(lv_event_t * e)
{
	// Your code here
}

void p_event_cb(lv_event_t * e)
{
	// Your code here
}

void add_event_cb(lv_event_t * e)
{
	// Your code here
}

void sub_event_cb(lv_event_t * e)
{
	// Your code here
}

void profile_event_cb(lv_event_t * e)
{
	// Your code here
}

void logger_start_event_cb(lv_event_t * e)
{
	// Your code here
}

void message_event_cb(lv_event_t * e)
{
	// Your code here
}
