// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: RoboTricklerUI

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView1, lv_pct(100));
lv_obj_set_height( ui_TabView1, lv_pct(100));
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Trickler");

ui_ButtonStart = lv_btn_create(ui_TabPage1);
lv_obj_set_width( ui_ButtonStart, 100);
lv_obj_set_height( ui_ButtonStart, 50);
lv_obj_set_align( ui_ButtonStart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonStart, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_LabelStart = lv_label_create(ui_ButtonStart);
lv_obj_set_width( ui_LabelStart, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStart, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelStart, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStart,"Start");
lv_obj_set_style_text_font(ui_LabelStart, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Powder");

ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Settings");

lv_obj_add_event_cb(ui_ButtonStart, ui_event_ButtonStart, LV_EVENT_ALL, NULL);

}
